spring:
  r2dbc:
    url: r2dbc:mysql://${FOOD_DB_HOST:localhost}:${FOOD_DB_PORT:3306}/${FOOD_DB_NAME:food_reactive}${FOOD_DB_ADDITIONAL_OPTIONS:?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
    name: ${FOOD_DB_NAME:food_reactive}
    username: ${FOOD_DB_USERNAME:root}
    password: ${FOOD_DB_PASSWORD:1234}

  kafka:
    bootstrap-servers: ${FOOD_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topics:
    city-event:
      name: ${FOOD_KAFKA_ENV_PREFIX:DEV}-city.event.upserted
      partitions: ${FOOD_KAFKA_TOPIC_CITY_EVENT_PARTITIONS:1}
      replicas: ${FOOD_KAFKA_TOPIC_CITY_EVENT_REPLICAS:1}
    city-event-retry:
      name: ${FOOD_KAFKA_ENV_PREFIX:DEV}-city.event.upserted.RETRY
      partitions: ${FOOD_KAFKA_TOPIC_CITY_EVENT_RETRY_PARTITIONS:1}
      replicas: ${FOOD_KAFKA_TOPIC_CITY_EVENT_RETRY_REPLICAS:1}
    city-event-dlt:
      name: ${FOOD_KAFKA_ENV_PREFIX:DEV}-city.event.upserted.DLT
      partitions: ${FOOD_KAFKA_TOPIC_CITY_EVENT_RETRY_PARTITIONS:1}
      replicas: ${FOOD_KAFKA_TOPIC_CITY_EVENT_RETRY_REPLICAS:1}
    state-event:
      name: ${FOOD_KAFKA_ENV_PREFIX:DEV}-state.event.upserted
      partitions: ${FOOD_KAFKA_TOPIC_STATE_EVENT_PARTITIONS:1}
      replicas: ${FOOD_KAFKA_TOPIC_STATE_EVENT_REPLICAS:1}
    state-event-retry:
      name: ${FOOD_KAFKA_ENV_PREFIX:DEV}-state.event.upserted.RETRY
      partitions: ${FOOD_KAFKA_TOPIC_STATE_EVENT_RETRY_PARTITIONS:1}
      replicas: ${FOOD_KAFKA_TOPIC_STATE_EVENT_RETRY_REPLICAS:1}
    state-event-dlt:
      name: ${FOOD_KAFKA_ENV_PREFIX:DEV}-state.event.upserted.DLT
      partitions: ${FOOD_KAFKA_TOPIC_STATE_EVENT_RETRY_PARTITIONS:1}
      replicas: ${FOOD_KAFKA_TOPIC_STATE_EVENT_RETRY_REPLICAS:1}

flyway:
  url: jdbc:mysql://${FOOD_DB_HOST:localhost}:${FOOD_DB_PORT:3306}/${FOOD_DB_NAME:food_reactive}${FOOD_DB_ADDITIONAL_OPTIONS:?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
  schemas: ${FOOD_DB_NAME:food_reactive}
  username: ${FOOD_DB_USERNAME:root}
  password: ${FOOD_DB_PASSWORD:1234}
  baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
